#  Jekyll Configuration

title: "Esteban Naranjo -- Data & AI Developer"
description: "BSc Data Science and Artificial Intelligence"
email: "enaranjo.eu@gmail.com"

url: "https://estebann23.github.io"
baseurl: ""

theme: null
plugins: []

social:
  github: "https://github.com/estebann23"
  linkedin: "https://linkedin.com/in/naranjo-esteban"
  kaggle: ""
  twitter: ""

# Projects

projects:
  - title: "Bachelor Thesis - KG-Embeddings for Explainable Recommendations"
    description: "Building a Knowledge Graph and implementing KG-embeddings using Python and Neo4j to generate explainable, transparent and personalized restaurant recommendations using extracted dietary and allergy constraints."
    tags: [Knowledge Graphs, Recommender Systems, Explainable AI (XAI)]
    url: "https://github.com/estebann23/kg-embeddings-recommender"
    repo: 
    year:

  - title: "Handwritten Digits Recognition"
    description: "Image recognition and processing of +17000 labelled handwritten Hindi numeral digits (0-9). Trained models using techniques Random Forests, Convolutional Neural Networks (CNN) for digits prediction with 99.86% accuracy on the validation set."
    tags: [Image Processing, OpenCV, Tensorflow]
    url: "https://github.com/estebann23/imagevideoprocessing-g23"
    repo: 
    year:

  - title: "Checkers AI Game Engine"
    description: "Developed a game engine for a checkers game using Java and JavaFX. Implemented multi-agent playing environment using adversarial search techniques (Alpha-Beta search, Minimax)."
    tags: [Game-Playing AI, MCTS, Multi-Agent Environments]
    url: "https://github.com/estebann23/frisianGame"
    repo: 
    year:

  - title: "Pizza Delivery App"
    description: "Developed a full-stack Java application for pizza delivery and stock management. Implemented relational databases using MySQL for data storage and connection with the core application with MySQL Connector."
    tags: [Java, Relational Databases, SQL]
    url: "https://github.com/estebann23/emiliapizza"
    repo:
    year:

# CV
cv_download_url: "assets/cv.pdf"

# Markdown & Highlighting
markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor